export const dummySkilll = [
  "Manufacturer",
  "Stockist",
  "Agent",
  "Freight Forwarder",
  "Research and Development Consultant",
  "Manufacturer",
  "Stockist",
  "Agent",
  "Freight Forwarder",
  "Research and Development Consultant",
  "Manufacturer",
  "Stockist",
  "Agent",
  "Freight Forwarder",
  "Research and Development Consultant",
  "Manufacturer",
  "Stockist",
  "Agent",
  "Freight Forwarder",
  "Research and Development Consultant",
  "Manufacturer",
  "Stockist",
  "Agent",
  "Freight Forwarder",
  "Research and Development Consultant",
  "Manufacturer",
  "Stockist",
  "Agent",
  "Freight Forwarder",
  "Research and Development Consultant",
];
export const headingTable = [
  "Name of Firm",
  "Type of Partnership"
];
